os:
  - linux
  - osx

osx_image: xcode8.3
dist: trusty
language: node_js
node_js:
  - 7.10.0

# before_install:
#  - brew update
#  - brew install gnu-tar graphicsmagick xz
#  - brew install wine --without-x11
#  - brew install mono

before_install:
  - brew install rpm

install:
  - cd client
  - npm install --silent
  - npm run build
  - cd ../server
  - npm install --silent
  - npm run build
  - cd ../electron
  - npm install --silent
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then npm run build:mac; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then npm run build:linux; fi