os:
- linux
- osx
osx_image: xcode8.3
dist: trusty
language: node_js
node_js:
- 7.10.0

install:
- cd client
- npm install --silent
- ./node_modules/.bin/ng build --prod --aot
- cd ../server
- npm install --silent
- npm run build
- cd ../electron
- npm install --silent
- npm run build
- cd ../

# Needed for running e2e tests on Linux
#before_script:
#  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0; fi
#  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh -e /etc/init.d/xvfb start; fi
#  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sleep 3; fi

script:
  - cd electron
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; npm run test:e2e; fi
  - cd ../

deploy:
  - provider: releases
    skip_cleanup: true
    overwrite: true
    api_key:
      secure: a5m10uoTD9bUej44Q3XVE91wZII44DFmOmU45K4gxAaoInLiAClhykfvRh23DO+CQ0krGAA8V7OC4OQICBT7C00Y4ajH0i1WucZGnT7n7wSeRKFXay8IWMrnV3dkYzqqnuFf2wPqOERB9BFmIcPjp6cbjb1G7nGGudNboLAYB7SpJrOr8M/NcFI4+x/8uRqoEZaeJYFZEmJtWi2cVweYzx++gtnnesZNCb+HwEZALp6iah5MGwWwYWrvEuAW9fYyKsUHSdv8vbtazWVAKF0AZ/EwkYCo6xVjyUKDx/q5pNANiYPv/1TVI5lf21iVbVqvUVQnQKcGdXpqFvFtCBdVVFzWLRk/Lq4afKgYbz0osJdf6WFngheM47ZmCTM4A1fYGgjfiNVMo7zBYn5KmERJ1u1pzyf4au7zqiUHmlSR7GlmVlCsD03ogvEXv9fjDwiZh2z0KrDE9ghZ1QPI39m0o0Y3I5bC80TIelcKzkyX8hIk6/DQREjN8Y3LGTIfXNuT14Q57LFJJ/Wn1y0oBu9UYF1iHbuLsrj/HaVuarSV3r8z2dTcCRqVt53QIAtZMamuPcqvkn96xTjvgkJ2Yg2/vUfROQY3gD1WgifMs+A0c22G8x2JTFn7qN2g2xjWtnMBptIgTamJPWw9CRB+RcF23tLwRyaAe5ilSWMiOuu+RXg=
    file: dist/TradeJS-0.0.1.dmg
    on:
      condition: $TRAVIS_OS_NAME == "osx"
      tags: true
      repo: DutchKevv/TradeJS
      branch:
        - master
        - development
  - provider: releases
    skip_cleanup: true
    overwrite: true
    api_key:
      secure: a5m10uoTD9bUej44Q3XVE91wZII44DFmOmU45K4gxAaoInLiAClhykfvRh23DO+CQ0krGAA8V7OC4OQICBT7C00Y4ajH0i1WucZGnT7n7wSeRKFXay8IWMrnV3dkYzqqnuFf2wPqOERB9BFmIcPjp6cbjb1G7nGGudNboLAYB7SpJrOr8M/NcFI4+x/8uRqoEZaeJYFZEmJtWi2cVweYzx++gtnnesZNCb+HwEZALp6iah5MGwWwYWrvEuAW9fYyKsUHSdv8vbtazWVAKF0AZ/EwkYCo6xVjyUKDx/q5pNANiYPv/1TVI5lf21iVbVqvUVQnQKcGdXpqFvFtCBdVVFzWLRk/Lq4afKgYbz0osJdf6WFngheM47ZmCTM4A1fYGgjfiNVMo7zBYn5KmERJ1u1pzyf4au7zqiUHmlSR7GlmVlCsD03ogvEXv9fjDwiZh2z0KrDE9ghZ1QPI39m0o0Y3I5bC80TIelcKzkyX8hIk6/DQREjN8Y3LGTIfXNuT14Q57LFJJ/Wn1y0oBu9UYF1iHbuLsrj/HaVuarSV3r8z2dTcCRqVt53QIAtZMamuPcqvkn96xTjvgkJ2Yg2/vUfROQY3gD1WgifMs+A0c22G8x2JTFn7qN2g2xjWtnMBptIgTamJPWw9CRB+RcF23tLwRyaAe5ilSWMiOuu+RXg=
    file: dist/tradejs_0.0.1_amd64.deb
    on:
      condition: $TRAVIS_OS_NAME == "linux"
      tags: true
      repo: DutchKevv/TradeJS
      branch:
        - master
        - development
