language: node_js
node_js:
  - 7.10.0
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

install:
  - cd client
  - npm install
  - npm run build
  - cd ../server
  - npm install
  - npm run build
  - cd ../electron
  - npm install
  - npm run build:mac
  - npm run build:windows