# Test against the latest version of this Node.js version
environment:
  nodejs_version: "7.9.0"

platform:
  - x64

# Install scripts. (runs after repo cloning)
install:
  - ps: Install-Product node 7.9.0 x64
#  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version)
  - cd client
  - npm install --silent
  - npm run build
  - cd ../server
  - npm install --silent
  - npm run build
  - cd ../electron
  - npm install --silent
  - npm run build
  - cd ../

# Don't actually build.
build: off

artifacts:
  - path: dist/TradeJS-0.0.1.exe
    name: setup

deploy:
  provider: GitHub
  force_update: true
  auth_token:
    secure: wG46ZMDX3zZXH6/ik+eVR8iJ6Yqww34vGKwgKdwpN2jWwiyYfkg3vjtnESa/ptSF
  draft: false
  artifect: setup
  prerelease: false
  on:
    appveyor_repo_tag: true