# Test against the latest version of this Node.js version
environment:
  nodejs_version: "7.10.0"

# Install scripts. (runs after repo cloning)
install:
  - cd client
  - npm install --silent
  - npm run build
  - cd ../server
  - npm install --silent
  - npm run build
  - cd ../electron
  - npm install --silent
  - npm run build:windows
  - cd ../

# Don't actually build.
build: off