os: unstable
environment:
  nodejs_version: "7.9.0"

platform:
  - x64

install:
  - ps: Install-Product node 7.9.0 x64
  - cd client
  - npm install --silent
  - npm run build
  - cd ../server
  - npm install --silent
  - npm run build
  - cd ../electron
  - npm install --silent
  - npm run build
  - cd ../

build: off

artifacts:
  - path: dist/TradeJS-0.0.1.exe
    name: setup

deploy:
  provider: GitHub
#  force_update: true
  auth_token:
    secure: wG46ZMDX3zZXH6/ik+eVR8iJ6Yqww34vGKwgKdwpN2jWwiyYfkg3vjtnESa/ptSF
#  draft: false
#  prerelease: false
  artifect: setup
#  on:
#    appveyor_repo_tag: true