# Test against the latest version of this Node.js version
environment:
  nodejs_version: "7.9.0"

platform:
  - x64

# Install scripts. (runs after repo cloning)
install:
  - ps: Install-Product node 7.9.0 x64
#  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version)
  - cd client
  - npm install --silent
  - npm run build
  - cd ../server
  - npm install --silent
  - npm run build
  - cd ../electron
  - npm install --silent
  - npm run build:windows
  - cd ../

# Don't actually build.
build: off

deploy:
  provider: GitHub
  force_update: true
  api_key:
    secure: a5m10uoTD9bUej44Q3XVE91wZII44DFmOmU45K4gxAaoInLiAClhykfvRh23DO+CQ0krGAA8V7OC4OQICBT7C00Y4ajH0i1WucZGnT7n7wSeRKFXay8IWMrnV3dkYzqqnuFf2wPqOERB9BFmIcPjp6cbjb1G7nGGudNboLAYB7SpJrOr8M/NcFI4+x/8uRqoEZaeJYFZEmJtWi2cVweYzx++gtnnesZNCb+HwEZALp6iah5MGwWwYWrvEuAW9fYyKsUHSdv8vbtazWVAKF0AZ/EwkYCo6xVjyUKDx/q5pNANiYPv/1TVI5lf21iVbVqvUVQnQKcGdXpqFvFtCBdVVFzWLRk/Lq4afKgYbz0osJdf6WFngheM47ZmCTM4A1fYGgjfiNVMo7zBYn5KmERJ1u1pzyf4au7zqiUHmlSR7GlmVlCsD03ogvEXv9fjDwiZh2z0KrDE9ghZ1QPI39m0o0Y3I5bC80TIelcKzkyX8hIk6/DQREjN8Y3LGTIfXNuT14Q57LFJJ/Wn1y0oBu9UYF1iHbuLsrj/HaVuarSV3r8z2dTcCRqVt53QIAtZMamuPcqvkn96xTjvgkJ2Yg2/vUfROQY3gD1WgifMs+A0c22G8x2JTFn7qN2g2xjWtnMBptIgTamJPWw9CRB+RcF23tLwRyaAe5ilSWMiOuu+RXg=
  artifact: dist/TradeJS-0.0.1.exe
  on:
    tags: true
    repo: DutchKevv/TradeJS
    branch: development
    appveyor_repo_tag: true