version: '3.3'

services:
  nginx:
    ports:
      - "4000:80"
    build:
      args:
        COPY_FILE: ./config/nginx.conf
    volumes:
      - ./images:/usr/src/app/images
      - ./client:/usr/src/app/client
  cache:
    build:
      args:
        NODE_ENV: development
    command:
      - /bin/sh
      - -c
      - |
          npm run install-shared
          npm i
          npm start
  client:
    build:
      args:
        NODE_ENV: development
    command:
      - /bin/sh
      - -c
      - |
          npm run install-shared
          npm i
          npm start
  gateway:
    build:
      args:
        NODE_ENV: development
    command:
      - /bin/sh
      - -c
      - |
          npm run install-shared
          npm i
          npm run start
    volumes:
      - ./images:/usr/src/app/images
  user:
    build:
      args:
        NODE_ENV: development
    command:
      - /bin/sh
      - -c
      - |
          npm run install-shared
          npm i
          npm run start
  comment:
    build:
      args:
        NODE_ENV: development
    command:
      - /bin/sh
      - -c
      - |
          npm run install-shared
          npm i
          npm run start
  event:
    build:
      args:
        NODE_ENV: development
    command:
      - /bin/sh
      - -c
      - |
          npm run install-shared
          npm i
          npm run start
  notify:
    build:
      args:
        NODE_ENV: development
    command:
      - /bin/sh
      - -c
      - |
          npm run install-shared
          npm i
          npm run start
  