version: '3.3'

services:
  client:
    build:
      args:
        NODE_ENV: development
    command:
      - /bin/sh
      - -c
      - |
          npm i
          npm start
  nginx:
    ports:
      - "4000:80"
  