version: '3.3'

services:
  cache:
    command:
      - /bin/sh
      - -c
      - |
          npm i
          npm run build
  client:
    build:
      args:
        NODE_ENV: development
    command:
      - /bin/sh
      - -c
      - |
          cd ../shared/modules/coinpush && npm i
          cd ../../../client
          npm i
          npm run build
  nginx:
    ports:
      - "80:80"
  