version: '3.3'

services:
  nginx:
    ports:
      - "80"
      - "443"
    volumes:
      - ./images:/usr/src/app/images
      - ./client:/usr/src/app/client
    build:
      args:
        COPY_FILE: ./config/nginx.prod.conf
  client:
    build:
      args:
        NODE_ENV: production
    environments:
      - NODE_ENV: production
    command:
      - /bin/sh
      - -c
      - |
          npm run install-shared
          npm i
          npm run build
          npm run prod
  gateway:
    build:
      args:
        NODE_ENV: production
    command:
      - /bin/sh
      - -c
      - |
          npm run install-shared
          npm i
          npm run build
          npm run prod
    volumes:
      - ./images:/usr/src/app/images
  cache:
    build:
      args:
        NODE_ENV: production
    command:
      - /bin/sh
      - -c
      - |
          npm i
          npm run build
          npm run prod
  event:
    build:
      args:
        NODE_ENV: production
    command:
      - /bin/sh
      - -c
      - |
          npm run install-shared
          npm i
          npm run build
          npm run prod
  notify:
    build:
      args:
        NODE_ENV: production
    command:
      - /bin/sh
      - -c
      - |
          npm run install-shared
          npm i
          npm run build
          npm run prod
  user:
    build:
      args:
        NODE_ENV: production
    command:
      - /bin/sh
      - -c
      - |
          npm run install-shared
          npm i
          npm run build
          npm run prod
  comment:
    build:
      args:
        NODE_ENV: production
    command:
      - /bin/sh
      - -c
      - |
          npm run install-shared
          npm i
          npm run build
          npm run prod
  