version: '3.3'

services:
  nginx:
    ports:
      - "4000:80"
    build:
      args:
        COPY_FILE: ./config/nginx.conf
    volumes:
      - ./images:/usr/src/app/images
      - ./client:/usr/src/app/client
      - ./server-nginx/pages:/usr/src/app/server-nginx/pages
  mongodb:
    ports:
      - "27017:27017"
  cache:
    environment:
      - NODE_ENV=development
    command:
      - /bin/sh
      - -c
      - |
          npm run install-shared
          npm i
          npm start
  client:
    environment:
      - NODE_ENV=development
    command:
      - /bin/sh
      - -c
      - |
          npm run install-shared
          npm i
          npm start
  client-app:
    environment:
      - NODE_ENV=development
    command:
      - /bin/sh
      - -c
      - |
          npm i
          chmod 777 -R /usr/local/android-sdk
          ./node_modules/.bin/cordova platform add android
          npm run build-android
  gateway:
    environment:
      - NODE_ENV=development
    command:
      - /bin/sh
      - -c
      - |
          npm run install-shared
          npm i
          npm run start
    volumes:
      - ./images:/usr/src/app/images
  user:
    environment:
      - NODE_ENV=development
    command:
      - /bin/sh
      - -c
      - |
          npm run install-shared
          npm i
          npm run start
  comment:
    environment:
      - NODE_ENV=development
    command:
      - /bin/sh
      - -c
      - |
          npm run install-shared
          npm i
          npm run start
  event:
    environment:
      - NODE_ENV=development
    command:
      - /bin/sh
      - -c
      - |
          npm run install-shared
          npm i
          npm run start
  notify:
    environment:
      - NODE_ENV=development
    command:
      - /bin/sh
      - -c
      - |
          npm run install-shared
          npm i
          npm run start
  